export const AuthTypes = {
  AUTH_SUCCESS: 'AUTH_SUCCESS',

  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',

  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',

  CHECK_TOKEN_ON_INIT: 'CHECK_TOKEN_ON_INIT',
  CHECK_TOKEN_ON_INIT_SUCCESS: 'CHECK_TOKEN_ON_INIT_SUCCESS',
  CHECK_TOKEN_ON_INIT_FAIL: 'CHECK_TOKEN_ON_INIT_FAIL',

  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAIL: 'GET_CURRENT_USER_FAIL',

  LOGOUT: 'LOGOUT',
};
